package com.araguacaima.open_archi.persistence.diagrams.core;

public enum ElementKind {
    //Commons
    PERSON,
    CONSUMER,
    DEFAULT,
    ITEM,
    FEATURE,
    //Architectures
    ARCHITECTURE_MODEL,
    LAYER,
    SYSTEM,
    CONTAINER,
    COMPONENT,
    DEPLOYMENT,
    //Bpms
    BPM_MODEL,
    BPM,
    POOL,
    LANE,
    ACTIVITY,
    //Flowcharts
    FLOWCHART_MODEL,
    FLOWCHART_INITIATOR,
    FLOWCHART_FINISHER,
    FLOWCHART_CONDITION,
    //Sequences
    SEQUENCE_MODEL,
    SEQUENCE,
    //Gantts
    GANTT_MODEL,
    GANTT,
    //EntityRelationships
    ENTITY_RELATIONSHIP_MODEL,
    ENTITY,
    ATTRIBUTE,
    //UMLClasses
    UML_CLASS_MODEL,
    CLASS,
    METHOD,
    FIELD,
    PARAMETER,
    //Components
    COMPONENT_MODEL,
    GROUP,
    ELEMENT
}
