package com.araguacaima.open_archi.persistence.diagrams.core;

public enum RelationshipKind {
    ARCHITECTURE_RELATIONSHIP,
    FLOWCHART_RELATIONSHIP,
    SEQUENCE_RELATIONSHIP,
    GANTT_RELATIONSHIP,
    ENTITY_RELATIONSHIP_RELATIONSHIP,
    UML_CLASS_RELATIONSHIP,
    BPM_RELATIONSHIP
}
