DELETE FROM diagrams.activity;
DELETE FROM diagrams.architecture_model_deploymentnodes;
DELETE FROM diagrams.attribute;
DELETE FROM diagrams.batchprocessing;
DELETE FROM diagrams.bulkprocessing;
DELETE FROM diagrams.concurrency;
DELETE FROM diagrams.connector;
DELETE FROM diagrams.connecttrigger;
DELETE FROM diagrams."constraint";
DELETE FROM diagrams.constraint_activities;
DELETE FROM diagrams.constraint_batchprocessing;
DELETE FROM diagrams.constraint_bulkprocessing;
DELETE FROM diagrams.constraint_concurrency;
DELETE FROM diagrams.constraint_database;
DELETE FROM diagrams.constraint_filetransfer;
DELETE FROM diagrams.constraint_rate;
DELETE FROM diagrams.container_components;
DELETE FROM diagrams.database;
DELETE FROM diagrams.deploymentnode_containerinstances;
DELETE FROM diagrams.taggable_ranks;
DELETE FROM diagrams.rank;
DELETE FROM diagrams.element_featureids;
DELETE FROM diagrams.element_properties;
DELETE FROM diagrams.entity_attributes;
DELETE FROM diagrams.feature_incoming_constraint;
DELETE FROM diagrams.feature_outgoing_constraint;
DELETE FROM diagrams.filetransfer;
DELETE FROM diagrams.flowchart_model_flowcharts;
DELETE FROM diagrams.gantt_model_gantts;
DELETE FROM diagrams.item_can_be_connected_from_ids;
DELETE FROM diagrams.item_can_be_connected_to_ids;
DELETE FROM diagrams.item_children_ids;
DELETE FROM diagrams.item_relationships;
DELETE FROM diagrams.lane_activities;
DELETE FROM diagrams.measurable;
DELETE FROM diagrams.metadata;
DELETE FROM diagrams.metadata_collaborators;
DELETE FROM diagrams.metadata_relatedwith;
DELETE FROM diagrams.metadata_responsibles;
DELETE FROM diagrams.metadata_usedin;
DELETE FROM diagrams.metadata_views;
DELETE FROM diagrams.model_classes;
DELETE FROM diagrams.model_entities;
DELETE FROM diagrams.model_pools;
DELETE FROM diagrams.pool_lanes;
DELETE FROM diagrams.range;
DELETE FROM diagrams.rate;
DELETE FROM diagrams.sequence_model_sequences;
DELETE FROM diagrams.taggable_cloned_by_ids;
DELETE FROM diagrams.umlclass_fields;
DELETE FROM diagrams.umlclass_methods;
DELETE FROM diagrams.umlfield;
DELETE FROM diagrams.umlmethod;
DELETE FROM diagrams.umlmethod_parameters;
DELETE FROM diagrams.umlparameter;
DELETE FROM diagrams.system_containers;
DELETE FROM diagrams.elementrole;
DELETE FROM diagrams.architecture_model_components;
DELETE FROM diagrams.architecture_model_containers;
DELETE FROM diagrams.architecture_model_systems;
DELETE FROM diagrams.architecture_model_layers;
DELETE FROM diagrams.layer_systems;
DELETE FROM diagrams.layer_containers;
DELETE FROM diagrams.layer_components;
DELETE FROM diagrams.system_systems;
DELETE FROM diagrams.system_containers;
DELETE FROM diagrams.system_components;
DELETE FROM diagrams.container_containers;
DELETE FROM diagrams.models;
DELETE FROM diagrams.compositeelement;
DELETE FROM diagrams.image;
DELETE FROM diagrams.shape_color_schemes;
DELETE FROM diagrams.shape;
DELETE FROM diagrams.point;
DELETE FROM diagrams.shape;
DELETE FROM diagrams.diagram_type_element_shapes;
DELETE FROM diagrams.element_shape_color_schemes;
DELETE FROM diagrams.elementshape;

DELETE FROM meta.metainfo_history_ids CASCADE;
DELETE FROM meta.metainfo CASCADE;
DELETE FROM meta.history CASCADE;
DELETE FROM meta.account_roles CASCADE;
DELETE FROM meta.role CASCADE;
DELETE FROM meta.version CASCADE;
DELETE FROM meta.view CASCADE;
DELETE FROM meta.avatar CASCADE;